name: Scrape and Update CSV

on:
  schedule:
    - cron: '0 12 */3 * *' # Запуск раз на три дні о 12:00 UTC (14:00 CEST)
  workflow_dispatch:      # Дозволяє запуск вручну

permissions:
  contents: write  # Додано для дозволу запису

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scrape script
        run: python price_finder.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add car_prices.csv progress.txt
          git commit -m "Update car_prices.csv and progress $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
