name: Scrape and Update CSV

on:
  schedule:
    - cron: '0 12 */3 * *'  # Запуск кожні 3 дні о 12:00 UTC
  workflow_dispatch:         # Дозволяє запускати вручну

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Крок 1: Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # Крок 2: Налаштування Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Версія Python

      # Крок 3: Встановлення залежностей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Крок 4: Запуск скрипта
      - name: Run scrape script
        run: python scrape.py

      # Крок 5: Коміт і пуш змін до CSV
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add car_prices.csv
          git commit -m "Update car_prices.csv $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
